### ISSUE TITLE
Different fallback options on quality option

### ISSUE THREAD

**Issue by LeLobster** [freaktechnik/justintv-stream-notifications#117]
>Another thing is that having medium in the livestreamer quality messes with both Youtube and Hitbox, as those don't have medium available as quality options.
Would it be possible to add the ability to add different fallback options for different platforms?
Like 480p for Hitbox, 720p for youtube? Or is that too difficult/impossible to implement?

Because falling back to always using 'best' for all could be problematic for people with monthly bandwidth caps.
Hitbox streams on 1080p, youtube 720/1080p, Twitch running on Source. That consumes a lot of bytes.
Not necessarily a problem for me (although my casual laptop does sometimes have problems viewing Twitch from source), but i can image it being problematic for some people.

**Comment by freaktechnik** [comment]
Okay, so my proposed solution (for now) is the wollowing:
You can define a quality per channel, which will be used instead of the default quality. This lets you use fine-grained control on channels that support it. Since the channels-manager supports multi-selection and filters it is easy to apply a preset to all channels of a certain provider etc.

This is better than just having presets per provider - however having a preset per provider would be beneficial too. Since there is currently nothing that is a provider-specific settings that exists for every provider there is no UI or similar for it, so I'd rather not have that.

As a workaround you can use the `--stream-sorting-excludes` argument in the default quality field to define custom rules for "best" if you are concerned about too high resolutions, for example. (so for example `best --stream-sorting-excludes ">720p,>medium"` and that should then work just fine (though I haven't tried it myself).

**Comment by Nhoise** [comment]
Can't get the stream sorting to work.
cmd just displays 
![hitboxquality](https://i.imgur.com/QAwYLbX.png)
and then shuts down. Both when using
``--stream-sorting-excludes ">720p,>medium"`` and 
``best --stream-sorting-excludes ">720p,>medium"``

--

I really think adding the options per provider is the way to go, though.
Isn't it possible to check which provider it is when you open a stream and then let your add-on decide the quality based on user preferred options.
Seems like a better option than to define everything separately by channel.

> Open stream with Livestreamer > Your add-on checks the stream provider (in this case Hitbox) >
Your add-on checks list of user defined quality for Hitbox > User has entered 720p > Your add-on checks if 720p is available > if not, it will check for the next available preferred quality. 480p > 
Opens livestreamer with quality 480p.

Don't know if this is possible at all, i'm not a dev. So please excuse when it's not.
Just something i got in my head.

**Comment by freaktechnik** [comment]
> Can't get the stream sorting to work.
As I said it will only work with 3.2.0.9999-pre2, which isn't released in the dev channel yet.

It is possible. However I think setting it per channel is better, since for example not all twitch channels have medium. Further I can not check what's available, at least I wouldn't know of it, I know that I can check if an URL can be handled by livestreamer.

**Comment by Nhoise** [comment]
> As I said it will only work with 3.2.0.9999-pre2, which isn't released in the dev channel yet.

My bad, didn't continue reading after you explained the possible workaround.

Yeah but that's what the fallback options are for. 
For example: this is what you would enter in the box for Twitch quality.
``medium, high`` and always have **best** as final fallback, so a stream will never fail to open.

But when using a non-available quality option, livestreamer will display which are available.
Is there no way to read that?

**Comment by freaktechnik** [comment]
I can see if the exit codes are constant between the unix and windows platforms (I'd hope so), and if yes, I could try to re-invoke livestreamer. However I have to look into if I can

 - Get the exit code of livestreamer
 - The exit code is the same on all platforms

**Comment by Nhoise** [comment]
Is livestreamer to blame for that? Because that seems to me to be pretty annoying to find a workaround for.

**Comment by freaktechnik** [comment]
I've gone for a little walk and decided to lay out, why exactly I'd rather not do it with a provider-specific stage, apart from the high-level reasoning of each channel possibly having different quality options:

What it takes to implement a channel-specific quality setting:

 - Add a quality field to each channel
 - Add a dialog in the channels manager to set that value
 - Use that value with livestreamer

What it takes to implement a providers-specific quality setting:
 - Add some kind of settings storage backend for providers, that works for each provider without specific inputs
 - Add some kind of interface to set the values in said backend
 - Use the value with livestreamer

Further I do not want comma separated lists. They are awful. There's so much that can go wrong:
 - `medium,source,` -> I have to check each entry is an actual preset.
 - Any kind of white-space (that's easy to handle)
 - `medium,source,medium` would create an infinite loop with simple handling. Needs advances handling to avoid that.

And there's probably more.

**Comment by Nhoise** [comment]
You know what you are talking about so i can only agree, as i have no idea what exactly goes into creating add-ons like this.
It's a shame though, because having it set per provider would be way more convenient for the end user.

So then your plan is to be able to apply quality via the channel manager? i.e. Right click > set quality
And have the default still always open streams on 'best'?

**Comment by Nhoise** [comment]
But when ``--stream-sorting`` will be functional in pre2, won't that negate the need for setting individual qualities?
As you can set ``--stream-sorting-excludes ">720p,>medium"`` So Hitbox and youtube will never open above 720p and Twitch won't go above medium.
Then only what is needed is what will happen when a, let's say medium, is not available on a stream.

Though. the same question would count when you would apply the thing you talk about in your first comment in this thread.
What will happen if someone sets the individual quality for a channel to medium, but medium is not available?
because
> using --default-stream=best and medium on a channel without medium sadly doesn't fall back to best.

**Comment by freaktechnik** [comment]
I'd have it fallback to the default thing defined in the prefs and then best. If I can get fallbacks to work. I just don't want to parse complicated fallback chains.

**Comment by Nhoise** [comment]
Yeah, see. If you'd be able to get one fallback option able to work then all you need is ``--stream-sorting-excludes ">720p,>medium"`` to fix the *issue* of streams displaying in too high res.
or w/e a certain person would set for ``--stream-sorting``
Right?

**Comment by freaktechnik** [comment]
Well, I don't even see why you'd need one fallback, since your set quality would be just the ---stream-sorting-exclude option, and livestreamer would fall back to best.

> That would completely negate the need to set individual quality prefs

Only for your excact use-case.

**Comment by Nhoise** [comment]
When a stream doesn't have ``medium`` available and you have ``--stream-sorting-exclude ">720p,>medium"`` it won't auto go to the next quality. Right?
And because ``--default-stream best`` and ``stream sorting`` don't work together you need a different method for a fallback quality if possible.
So  for example: if this option would be implemented and i'd enter ``">720p,>medium"`` i wouldn't be able to open UnderscoreTrix's stream via your add-on, because he doesn't have medium quality available.

I might be making this a lot more complicated then it really is, though.

**Comment by freaktechnik** [comment]
`--default-stream` and `--stream-sorting-exclude` work together, that's why it works with 9999-pre2.

**Comment by Nhoise** [comment]
With the way it's explained in the livestreamer docs i thought they didn't.
> Open this stream when no stream argument is specified, e.g. “best”.

I understood that as it'll only accept ``--default-stream`` if no other quality parameter is set

**Comment by freaktechnik** [comment]
---stream-sorting-exclude is not a quality parameter. It changes the rules for what best and worst mean.

**Comment by Nhoise** [comment]
twitch.tv/rockleesmile --stream-sorting-exclude ">720p,>medium" --default-stream best
[cli][info] Found matching plugin twitch for URL twitch.tv/rockleesmile
[cli][info] Available streams: audio, high, low, medium (best), mobile (worst), source
[cli][info] Opening stream: medium (hls)
...

twitch.tv/underscoretrix --stream-sorting-exclude ">720p,>medium" --default-stream best
[cli][info] Found matching plugin twitch for URL twitch.tv/underscoretrix
error: The specified stream(s) 'best' could not be found.
Available streams: audio, source

>  freaktechnik commented 3 hours ago
Well, I don't even see why you'd need one fallback,

This is why.
If ``--stream-sorting`` overwrites what ``best`` is considered to be, then it''ll give exactly this problem with my setup.
Or am i missing something obvious?

**Comment by freaktechnik** [comment]
The default fallback thing is in the now released -pre3. It behaves as described on http://jtvn.humanoids.be/help/livestreamer/.

**Comment by Nhoise** [comment]
Using pre4, all i can say is: perfect
Tested on Twitch, Hitbox and youtube and it's working as expected.
``about:config``
> livestreamer_quality ``medium,480p``

Hitbox and YT never go above ``480p`` and Twitch opens in ``medium``, or when not available it closes the cmd window and reopens with ``best``.
Very nice

**Comment by freaktechnik** [comment]
Okay, cool! I'll add listing qualities to the docs then, didn't know that works.

On naming: I don't want to migrate values, and honestly don't care about naming in about:config. The name of the pref comes from before I had the idea of the context menu items.
