### ISSUE TITLE
[Request] Execute a program upon stream detection

### ISSUE THREAD

**Issue by broski93** [freaktechnik/justintv-stream-notifications#230]
Would it be possible to add such a feature? It could be used to execute a program, for example rtmpdump or ffmpeg (through a batch file) whenever a stream goes live, thus allowing to record it automatically. And this is only one of the possible applications.

**Comment by freaktechnik** [comment]
This is impossible for security reasons (extensions will not be able to execute arbitrary executables from Firefox 57). I would recommend using dedicated software for a job like recording streams in any case, since a browser should not be considered a reliable runtime to execute arbitrary code on a machine in general.
