### ISSUE TITLE
Removing Twitch channels doesn't work anymore

### ISSUE THREAD

**Issue by Daisenki** [freaktechnik/justintv-stream-notifications#309]
I can't remove Twitch channels anymore at version 3.4.0 now, if I remove the channels at the manager its gone in the list, closing the manager and reopening it the removed channel is back at the list. The addon doesn't save the removed Twitch channel.

Add a new Twitch channel works normal, it stays on list after closing the manager and reopening it.

 - *Operating System*: Windows 10 - 1703 15063.540
 - *Firefox Version*: 54.0.1 (64-bit)
 - *Extension Version*: 3.4.0

Debug Dump Shift + Click on the "Help" button does nothing at my Firefox.

**Comment by freaktechnik** [comment]
This isn't actually a bug new to this version. It is most likely caused by the indexedDB of the extension being damaged.

There are two things to try here:
 1. Pause the queue and then remove it, wait a minute or so and then re-enable the queue.
 2. Disable the extension and re-enable it. This will re-import all the channels from the state they were in pre-3.4.0

**Comment by Daisenki** [comment]
Problem fixed with disable and re-enable the addon, removed channels now stay gone like it should. 

Thanks for the help! :)
