### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Daisenki** [freaktechnik/justintv-stream-notifications#389]
Is there any way to get the notification on every monitor? The notification shows only at the desktop monitor and sometimes I don't see it because I work on the other monitor...

Can you do anything with the notification or is that a Firefox thing? I also would be cool if I can select left or right, because the notification blocks sometimes the Twitch chat input box if it shows up, its a bit annoying.

**Comment by freaktechnik** [comment]
That is a thing of the notification system used. On Mac OS and Linux that's probably your native notification daemon. On Windows and some Linux systems that's Firefox's own system. Which will by default show up in the bottom right of your primary monitor (doesn't really work on linux because how X does multimonitor afaik) and if you've maximized the Firefox window in the top right iirc.

If you want to customize that you'd have to rely on Firefox options.

**Comment by freaktechnik** [comment]
(If you don't want to miss notifications I can recommend https://addons.mozilla.org/firefox/addon/notification-sound/ ;)
