### ISSUE TITLE
Sometimes notification does not fade away

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [freaktechnik/justintv-stream-notifications#92]
Notifications last forever sometimes, even after browser closed.

![stream-tagliato](https://cloud.githubusercontent.com/assets/10689739/7144312/0a548a86-e2e5-11e4-8697-881be1e5d20b.png)

**Comment by freaktechnik** [comment]
This is not an issue with the extension itself, but instead a problem with your OS's notification manager, or firefox's (your screenshot looks like its a notification directly from firefox, because your system's libnotify doesn't support actions). Most notification systems don't hide their notification while it thinks the mouse is over the notification.
